DROP DATABASE IF EXISTS STUDENT;
CREATE DATABASE IF NOT EXISTS STUDENT;

USE STUDENT;

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT(
    DEPTID INT NOT NULL,
    DEPTNAME VARCHAR(30) NOT NULL,
    BUDGET INT NOT NULL,
    MANAGERID INT NOT NULL,

    PRIMARY KEY (DEPTID)
);

DROP TABLE IF EXISTS EMPLOYE;
CREATE TABLE EMPLOYE(
    EMPID INT NOT NULL,
    DOB DATE NOT NULL,
    SALARY INT NOT NULL,
    EMPNAME VARCHAR(30) NOT NULL,
    DEPTID INT NOT NULL,

    PRIMARY KEY (EMPID) ,
    FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT (DEPTID)
);